--- elvis-tiny-1.4.orig/Makefile.mix	1991-08-04 21:20:19.000000000 +0000
+++ elvis-tiny-1.4/Makefile.mix	2012-06-29 20:26:25.262635031 +0000
@@ -36,6 +36,30 @@
 #	DUMMY	usually nothing, but OS9 needs "dummy"
 #	DOC	name of "doc" directory, with a trailing slash
 
+#---- These settings are recommended for Linux ----
+O=	.o
+E=
+EXTRA=
+EXTRA2=
+LIBS=	-ltinfo
+BIN=	/usr/bin
+CFLAGS=	-O2 -DM_SYSV -DCRUNCH -DNO_MKEXRC -DNO_CURSORSHAPE -DNO_CHARATTR \
+	-DNO_SHOWMODE -DNO_MODELINE -DNO_OPTCOLS -DNO_DIGRAPH -DNO_ABBR \
+	-DNO_AT -DNO_SENTENCE -DNO_ERRLIST -fsigned-char $(EXTRA_CFLAGS)
+OF=	-o 
+RF=	-c
+DATE=	-DDATE=\'\"`date`\"\'
+EVAL=	eval 
+PROGS=	elvis
+CHMEM=	
+SORT=	-DSORT
+INST=	inst.unix
+RM=	rm -f
+PR1=	refont -c
+PR2=	| lpr
+DUMMY=
+DOC=	doc/
+
 #---- These settings are recommended for System-V UNIX and SCO XENIX-386 ----
 #O=	.o
 #E=
